Made required changes. Tests are passing.
makersacademy/acebook-remote-july-2017 pull request #24
Opened 2017-08-23 14:36 UTC by meta-morpho-sys

Please  review and comment if there is anything else I could do here.

2017-08-23 16:15 UTC, i-hardy approved these changes
:shipit:

2017-08-23 16:18 UTC, paulmillen commented on app/views/devise/registrations/edit.html.erb
> +  </div></br>
I believe br's don't need '/' ?

2017-08-23 21:07 UTC, meta-morpho-sys commented on app/views/devise/registrations/edit.html.erb
> +  </div></br>
yes, thank you for your suggestion. I will do that in future.

2017-08-23 21:51 UTC, aballal approved these changes

2017-08-24 08:38 UTC, petrakh approved these changes
:shipit:

2017-08-24 09:50 UTC, dbugsy requested changes

2017-08-24 09:50 UTC, dbugsy commented on app/views/devise/registrations/edit.html.erb
> +  </div></br>
`</br>` shouldn't really be necessary - all the styling and positioning should be done by CSS anyways. If you remove them, does it break?

2017-08-24 13:30 UTC, meta-morpho-sys commented on app/views/devise/registrations/edit.html.erb
> +  </div></br>
Thank you Dan for our comment.

When I remove them, the fields become all attached (like compressed). Of course, when the CSS will be done, the problem will cease existing. If you are ok with this I will proceed to making the change.

2017-08-24 16:15 UTC, dbugsy approved these changes

2017-08-25 09:11 UTC, merged