Comments can be added to posts
makersacademy/acebook-remote-july-2017 pull request #3
Opened 2017-08-21 16:18 UTC by i-hardy

Not yet able to edit or delete comments

2017-08-21 16:28 UTC, dbugsy requested changes

2017-08-21 16:28 UTC, dbugsy commented on spec/controllers/comments_controller_spec.rb
> +      expect(Comment.find_by(text: "Hello, world!")).to be
Unfinished line?

2017-08-21 16:28 UTC, dbugsy commented on spec/features/users_can_post_comments.rb
> +  end
nice!

2017-08-21 16:28 UTC, dbugsy commented on spec/helpers/comments_helper_spec.rb
> +# end
Unused, can delete this

2017-08-21 16:28 UTC, dbugsy commented on spec/models/comment_spec.rb
> +  it { is_expected.to be }
expected to be what?

2017-08-21 16:28 UTC, dbugsy commented on app/controllers/comments_controller.rb
> +  end
good use of permit

2017-08-21 16:28 UTC, dbugsy commented on app/controllers/comments_controller.rb
> +    if @comment.save
`create` will also save. better to use `.new`.

2017-08-22 10:00 UTC, i-hardy commented
Changes made and testing bug fixed, please review @dbugsy

2017-08-22 13:01 UTC, dbugsy approved these changes

2017-08-22 13:01 UTC, dbugsy commented
:shipit: :shipit: 

You'll need to resolve conflicts in order to merge - you have admin, so this should be possible. Nice work!

2017-08-22 13:08 UTC, petrakh approved these changes
:shipit:

2017-08-22 13:10 UTC, langphil approved these changes
:shipit:

2017-08-22 13:10 UTC, merged